### ISSUE TITLE
Let burning oil turn into acid

### ISSUE THREAD

**Issue by cameracameraboo23** [MaxBittker/sandspiel#80]
When the oil is burning, let the smoke, if enough, turn into acid.

**Comment by onlymx13** [comment]
Why do this? Smoke in this game is not substantial, so having it turn into something would be weird because it would create mass out of nowhere. Also, creating acid from nowhere would not be fun, since it would destroy the oil, the fire it burns with, the floor it rests on, and anything above it. Overall I don't support this change because smoke and acid may have this relationship in real life, but the way they work in-game would make this very unfun.

**Comment by cameracameraboo23** [comment]
If enough, turn into a bit of acid. maybe only turn it into acid if there's rocket in the burning oil

**Comment by catgofire** [comment]
This game is cell-based -- a single pixel can only make decisions based on cells that are directly touching it. So there's no way for smoke (which isn't even an element, just a visual flourish that doesn't affect anything around it) to know what's in the oil it came from.

**Comment by MaxBittker** [comment]
I like elements turning into other elements (like oil and nitro in some older sand games) but going to close this because i dont agree for acid
